openapi: '3.0.0'
info:
  version: '0.1.0'
  title: 'Website API'
  description: 'API for the PIES at UCLA organization website.'
  
paths:
  /users:
    $ref: 'paths/Users.yaml'
  /users/{userId}:
    $ref: 'paths/User.yaml'
  /events:
    $ref: 'paths/Events.yaml'
  /events/{eventId}:
    $ref: 'paths/Event.yaml'
  /events/{eventId}/picture:
    $ref: 'paths/EventPicture.yaml'
  /board:
    $ref: 'paths/BoardMembers.yaml'
  /board/{userId}:
    $ref: 'paths/BoardMember.yaml'
  /board/{userId}/picture:
    $ref: 'paths/BoardMemberPicture.yaml'
  /board/{userId}/resume:
    $ref: 'paths/BoardMemberResume.yaml'
  /alumni:
    $ref: 'paths/Alumnus.yaml'
  /alumni/{alumniId}:
    $ref: 'paths/Alumni.yaml'
  /resources:
    $ref: 'paths/Resources.yaml'
  /resources/{resourceId}:
    $ref: 'paths/Resource.yaml'
  /resources/{resourceId}/picture:
    $ref: 'paths/resourcePicture.yaml'
  
components:
  schemas:
    $ref: "./schemas/index.yaml"
  securitySchemes:
    OAuth2_PIES_Website:
      type: oauth2
      description: This API uses Google OAuth2 to perform authentication.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth # Full URL with all queries/parameters in "PIES Website: Authentication Flow" design doc
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            userinfo.email: See your primary Google Account email address.
            userinfo.profile: See your personal info, including any personal info you've made publicly available.
security:
  - OAuth2_PIES_Website:
    - userinfo.email
    - userinfo.profile